### ISSUE TITLE
Installing oddt from poetry is not possible

### ISSUE THREAD

**Issue by ElricleNecro** [oddt/oddt#164]
Due to the `__version__` import in the `setup.py`, tools like [poetry](https://github.com/python-poetry/poetry) are not able to install `oddt` as it needs the `six` module before the `setuptools` could install it:
```terminal
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      Traceback (most recent call last):
        File "/miniconda/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/miniconda/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/miniconda/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-4mqoeypw/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-4mqoeypw/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-4mqoeypw/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 484, in run_setup
          self).run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-4mqoeypw/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 3, in <module>
        File "/tmp/pip-install-9hsc6sfp/oddt_93477a5cb3044dcd928d72dc9218d0ea/oddt/__init__.py", line 17, in <module>
          import six
      ModuleNotFoundError: No module named 'six'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

The solution would be to modify the `oddt/__init__.py` file to remove the `six` import. I see two ways to do that:
- or completely remove the `six` module in here and use the `sys` module:
  ```python
  sys.version_info[0] == 3
  ```
  instead of `six.PY3`
- or move the import in the `if`-block inside the `get_version` function since this is only done if built from a git repository:
  ```python
  if os.path.isdir(home + '/../.git'):
      import six
      ...
  ```

**Comment by mwojcikowski** [comment]
By now six can be removed entirely. I will make a release and a quick followup to clenup six afterwards.

**Comment by ElricleNecro** [comment]
May I ask when do you plan to do the release?

**Comment by jimxliu** [comment]
Any ETA on the release?
