### ISSUE TITLE
pip installation failed - 

### ISSUE THREAD

**Issue by dansteiert** [oddt/oddt#169]
````
pip install oddt
Collecting oddt
  Using cached oddt-0.7.tar.gz (2.3 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-zfbgyl5u/oddt_6ad59df9037b4f8aa4b2510c3687bd8e/setup.py", line 3, in <module>
          from oddt import __version__ as VERSION
        File "/tmp/pip-install-zfbgyl5u/oddt_6ad59df9037b4f8aa4b2510c3687bd8e/oddt/__init__.py", line 17, in <module>
          import six
      ModuleNotFoundError: No module named 'six'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```


after running pip install six the installation worked for me ;)

**Comment by metric-space** [comment]
Two years (and more) too late but for anyone wondering why this is popping up and how to solve it,
the issue is in the `setup.py` specifically the part where it tries to import the package to get the VERSION

https://github.com/oddt/oddt/blob/bfbf9ea99768b556684dc99c6ac87a9f16b16f80/setup.py#L3

This pulls in the init file at the base and hence pulls in `six`
https://github.com/oddt/oddt/blob/bfbf9ea99768b556684dc99c6ac87a9f16b16f80/oddt/__init__.py#L17

That aside, a quick was to fork the repo and change the `setup.py` to be like the following:

https://github.com/metric-space/oddt/commit/8d3a014e9327bcde2dc45903c7307c8596157f7d

and of course `pip install git+https://github.com/<your_github_id>/oddt`

Is it the greatest fix? nope Does it get the job solved for the time being? yes

P.S. installing `six` prior to installing this package did not work for me (as in, did not trigger a successful build, the six error message continued to pop up). I am not sure how OP got it work as OP claims OP did without disabling build isolation 🤔

**Comment by metric-space** [comment]
Also see #164 ,  same issue and the person there is reporting the same thing. Problem with `setup.py`
