### ISSUE TITLE
AttributeError: module 'openbabel.openbabel' has no attribute 'OBElementTable'

### ISSUE THREAD

**Issue by nickyoungforu** [oddt/oddt#172]
Traceback (most recent call last):
  File "post_process.py", line 6, in <module>
    import oddt
  File "/home/pipeline/.local/lib/python3.6/site-packages/oddt/__init__.py", line 20, in <module>
    from oddt.toolkits import ob
  File "/home/pipeline/.local/lib/python3.6/site-packages/oddt/toolkits/ob.py", line 59, in <module>
    GetVdwRad = ob.OBElementTable().GetVdwRad
AttributeError: module 'openbabel.openbabel' has no attribute 'OBElementTable'

**Comment by nikoniko90** [comment]
Check to see if you have multiple versions of OpenBabel present. I saw this when I had 2 installations, and the pre-3.0 obabel was run to check the version, even though I had used the latest (>=3.0) version of OpenBabel. Rearranging your PATH so that the newer obabel gets called should fix it.

**Comment by jssweller** [comment]
This could also arise from an error in checking for the obabel version in `toolkits/ob.py`:
```
try:
    __version__ = check_output(['obabel', '-V']).split()[2].decode('ascii')
except Exception as e:
    __version__ = ''
```
As you can see, `subprocess.check_output` is used to get the version number. If there is an error, the default version will be an empty string. Note that if obabel is installed in, for example, a conda environment, check_output will fail (or returns the version of a non-conda obabel installation). If you're on Windows, check_output also fails without `shell=True`. Later, this `__version__` is used for version checking:
```
if __version__ >= '3.0.0':
    GetVdwRad = ob.GetVdwRad
else:
    GetVdwRad = ob.OBElementTable().GetVdwRad
```
Here, an empty string will evaluate to false, so it's as if you have obabel version <'3.0.0'.  To work around this error, I changed the default value of `__version__` in `ob.py`:
```
try:
    __version__ = check_output(['obabel', '-V']).split()[2].decode('ascii')
except Exception as e:
    __version__ = '3.1.0'
```
